Update

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -1,37 +1,31 @@
 #!/usr/bin/env bash
 
-export PYTHONHASHSEED=22
-
-src_dir=$(dirname "$0")
-cd "$src_dir/../.."
+set -e
 
 # Parameterize
-PYTHON_VERSION=3.7.9
-GIT_REPO=https://github.com/runebase/runebase-electrum
-DIST_DIR="dist"
+PYTHON_VERSION=3.9.11
+GIT_REPO=https://github.com/runebaseproject/runebase-electrum
 BUILDDIR=/tmp/runebase-electrum-build
 PACKAGE="Runebase Electrum"
 VERSION=`git describe --tags --dirty --always`
-DMG_NAME="${DIST_DIR}/Runebase-electrum-${VERSION}.dmg"
+DMG_NAME="./dist/Runebase-electrum-${VERSION}.dmg"
 TEMP_DMG_NAME="$BUILDDIR/runebase-electrum.dmg"
-LIBSECP_VERSION="b408c6a8b287003d1ade5709e6f7bc3c7f1d5be7"
 
 #export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;
 
 export GCC_STRIP_BINARIES="1"
+export PYTHONDONTWRITEBYTECODE=1  # don't create __pycache__/ folders with .pyc files
 
 . "$(dirname "$0")/../build_tools_util.sh"
 
 CONTRIB_OSX="$(dirname "$(realpath "$0")")"
 CONTRIB="$CONTRIB_OSX/.."
-ROOT_FOLDER="$CONTRIB/.."
+PROJECT_ROOT="$CONTRIB/.."
 CACHEDIR="$CONTRIB_OSX/.cache"
 
 mkdir -p "$CACHEDIR"
+cd "$PROJECT_ROOT"
 
-
-
-which brew > /dev/null 2>&1 || fail "Please install brew from https://brew.sh/ to continue"
 which xcodebuild > /dev/null 2>&1 || fail "Please install Xcode and xcode command line tools to continue"
 
 # Code Signing: See https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html
@@ -72,19 +66,23 @@ function DoCodeSignMaybe { # ARGS: infoName fileOrDirName
 }
 
 
-export LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/sqlite/lib"
-export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite/include"
-
 info "Installing Python $PYTHON_VERSION"
-export PATH="~/.pyenv/bin:~/.pyenv/shims:~/Library/Python/3.7/bin:$PATH"
-if [ -d "${HOME}/.pyenv" ]; then
-  pyenv update
-else
-  curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash > /dev/null 2>&1
+PKG_FILE="python-${PYTHON_VERSION}-macosx10.9.pkg"
+if [ ! -f "$CACHEDIR/$PKG_FILE" ]; then
+    curl -o "$CACHEDIR/$PKG_FILE" "https://www.python.org/ftp/python/${PYTHON_VERSION}/$PKG_FILE"
 fi
-PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install -s $PYTHON_VERSION && \
-pyenv global $PYTHON_VERSION || \
-fail "Unable to use Python $PYTHON_VERSION"
+echo "c2073d44c404c661dadbf0cbda55c6e7d681baba9178ed1bdb126d34caa898a9  $CACHEDIR/$PKG_FILE" | shasum -a 256 -c \
+     || fail "python pkg checksum mismatched"
+sudo installer -pkg "$CACHEDIR/$PKG_FILE" -target / \
+    || fail "failed to install python"
+
+# sanity check "python3" has the version we just installed.
+FOUND_PY_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:3])))')
+if [[ "$FOUND_PY_VERSION" != "$PYTHON_VERSION" ]]; then
+    fail "python version mismatch: $FOUND_PY_VERSION != $PYTHON_VERSION"
+fi
+
+break_legacy_easy_install
 
 # create a fresh virtualenv
 # This helps to avoid older versions of pip-installed dependencies interfering with the build.
@@ -94,11 +92,12 @@ python3 -m venv $VENV_DIR
 source $VENV_DIR/bin/activate
 
 info "Installing build dependencies"
-python3 -m pip install --no-dependencies --no-warn-script-location -Ir ./contrib/deterministic-build/requirements-build-mac.txt \
-    || fail "Could not install build dependencies"
-
-info "Installing some build-time deps for compilation..."
-brew install autoconf automake libtool gettext coreutils pkgconfig
+python3 -m pip install --no-build-isolation --no-dependencies --no-warn-script-location \
+    -Ir ./contrib/deterministic-build/requirements-build-base.txt \
+    || fail "Could not install build dependencies (base)"
+python3 -m pip install --no-build-isolation --no-dependencies --no-warn-script-location \
+    -Ir ./contrib/deterministic-build/requirements-build-mac.txt \
+    || fail "Could not install build dependencies (mac)"
 
 info "Building PyInstaller."
 PYINSTALLER_REPO="https://github.com/pyinstaller/pyinstaller.git"
@@ -112,7 +111,7 @@ PYINSTALLER_COMMIT="40c9abce2d8de879e414fd377c933dccaab1e156"
         info "pyinstaller already built, skipping"
         exit 0
     fi
-    cd "$ROOT_FOLDER"
+    cd "$PROJECT_ROOT"
     ELECTRUM_COMMIT_HASH=$(git rev-parse HEAD)
     cd "$CACHEDIR"
     rm -rf pyinstaller
@@ -144,7 +143,7 @@ python3 --version
 echo -n "Pyinstaller "
 pyinstaller --version
 
-rm -rf ${DIST_DIR}
+rm -rf ./dist
 
 git submodule update --init
 
@@ -153,49 +152,56 @@ mkdir "$BUILDDIR"
 
 info "generating locale"
 (
-    if ! which msgfmt > /dev/null 2>&1; then
-        brew install gettext
-        brew link --force gettext
-    fi
-    cd "$ROOT_FOLDER"/electrum/locale
+    cd "$PROJECT_ROOT"/electrum/locale
     for i in ./*; do
-        dir="$ROOT_FOLDER"/electrum/locale/$i/LC_MESSAGES
+        dir="$PROJECT_ROOT"/electrum/locale/$i/LC_MESSAGES
         mkdir -p "$dir"
         msgfmt --output-file=$dir/electrum.mo $i/electrum.po || true
     done
 ) || fail "failed generating locale"
 
-info "Preparing for building libusb, libsecp256k1"
-brew install autoconf automake libtool
 
-info "building libusb"
-"$CONTRIB"/make_libusb.sh || fail "Could not build libusb"
-cp "$ROOT_FOLDER"/electrum/libusb-1.0.dylib contrib/osx
+if [ ! -f "$PROJECT_ROOT"/electrum/libsecp256k1.0.dylib ]; then
+    info "Building libsecp256k1 dylib..."
+    "$CONTRIB"/make_libsecp256k1.sh || fail "Could not build libsecp"
+else
+    info "Skipping libsecp256k1 build: reusing already built dylib."
+fi
+cp "$PROJECT_ROOT"/electrum/libsecp256k1.0.dylib "$CONTRIB"/osx
 
-info "building libsecp256k1"
+
+if [ ! -f "$PROJECT_ROOT"/electrum/libzbar.0.dylib ]; then
+    info "Building ZBar dylib..."
+    "$CONTRIB"/make_zbar.sh || fail "Could not build ZBar dylib"
+else
+    info "Skipping ZBar build: reusing already built dylib."
+fi
+cp "$PROJECT_ROOT"/electrum/libzbar.0.dylib "$CONTRIB"/osx
+
+
+if [ ! -f "$PROJECT_ROOT"/electrum/libusb-1.0.dylib ]; then
+    info "Building libusb dylib..."
+    "$CONTRIB"/make_libusb.sh || fail "Could not build libusb dylib"
+else
+    info "Skipping libusb build: reusing already built dylib."
+fi
+cp "$PROJECT_ROOT"/electrum/libusb-1.0.dylib "$CONTRIB"/osx
+
+
+info "Preparing for building libsecp256k1"
 "$CONTRIB"/make_libsecp256k1.sh || fail "Could not build libsecp"
-cp "$ROOT_FOLDER"/electrum/libsecp256k1.0.dylib contrib/osx
-
-info "Building CalinsQRReader..."
-d=contrib/osx/CalinsQRReader
-pushd "$d"
-rm -fr build
-# prefer building using xcode ourselves. otherwise fallback to prebuilt binary
-xcodebuild || cp -r prebuilt_qr build || fail "Could not build CalinsQRReader"
-popd
-DoCodeSignMaybe "CalinsQRReader.app" "${d}/build/Release/CalinsQRReader.app"
-
+cp "$PROJECT_ROOT"/electrum/libsecp256k1.0.dylib contrib/osx
 
 info "Installing requirements..."
-python3 -m pip install --no-dependencies --no-warn-script-location -Ir ./contrib/deterministic-build/requirements.txt \
+python3 -m pip install --no-build-isolation --no-dependencies --no-warn-script-location -Ir ./contrib/deterministic-build/requirements.txt \
     || fail "Could not install requirements"
 
 info "Installing hardware wallet requirements..."
-python3 -m pip install --no-dependencies --no-warn-script-location -Ir ./contrib/deterministic-build/requirements-hw.txt \
+python3 -m pip install --no-build-isolation --no-dependencies --no-warn-script-location -Ir ./contrib/deterministic-build/requirements-hw.txt \
     || fail "Could not install hardware wallet requirements"
 
 info "Installing dependencies specific to binaries..."
-python3 -m pip install --no-dependencies --no-warn-script-location -Ir ./contrib/deterministic-build/requirements-binaries-mac.txt \
+python3 -m pip install --no-build-isolation --no-dependencies --no-warn-script-location -Ir ./contrib/deterministic-build/requirements-binaries-mac.txt \
     || fail "Could not install dependencies specific to binaries"
 
 info "Installing eth requirements..."
@@ -203,22 +209,19 @@ python3 -m pip install -Ir ./contrib/deterministic-build/requirements-eth.txt --
     || fail "Could not install eth requirements"
 
 info "Building $PACKAGE..."
-python3 -m pip install --no-dependencies --no-warn-script-location . > /dev/null || fail "Could not build $PACKAGE"
+python3 -m pip install --no-build-isolation --no-dependencies --no-warn-script-location . > /dev/null || fail "Could not build $PACKAGE"
 
 info "Faking timestamps..."
-for d in ~/Library/Python/ ~/.pyenv .; do
-  pushd "$d"
-  find . -exec touch -t '200101220000' {} +
-  popd
-done
+find . -exec touch -t '200101220000' {} + || true
+
 
 info "Building binary"
-APP_SIGN="$APP_SIGN" pyinstaller --noconfirm --ascii --clean --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
+pyinstaller --noconfirm --ascii --clean --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
 
 info "Adding runebase URI types to Info.plist"
 plutil -insert 'CFBundleURLTypes' \
 	-xml '<array><dict> <key>CFBundleURLName</key> <string>runebase</string> <key>CFBundleURLSchemes</key> <array><string>runebase</string></array> </dict></array>' \
-	-- "${DIST_DIR}/${PACKAGE}.app/Contents/Info.plist" \
+	-- "./dist/${PACKAGE}.app/Contents/Info.plist" \
 	|| fail "Could not add keys to Info.plist. Make sure the program 'plutil' exists and is installed."
 
 #DoCodeSignMaybe "app bundle" "${DIST_DIR}/${PACKAGE}.app" "$APP_SIGN" # If APP_SIGN is empty will be a noop
@@ -226,7 +229,7 @@ plutil -insert 'CFBundleURLTypes' \
 info "Creating .DMG"
 hdiutil create -size 300m -fs HFS+ -volname "${PACKAGE}" -ov ${TEMP_DMG_NAME}
 hdiutil mount ${TEMP_DMG_NAME}
-cp -R "${DIST_DIR}/${PACKAGE}.app" "/Volumes/${PACKAGE}/${PACKAGE}.app"
+cp -R "./dist/${PACKAGE}.app" "/Volumes/${PACKAGE}/${PACKAGE}.app"
 ln -s /Applications "/Volumes/${PACKAGE}/Applications"
 
 hdiutil detach "/Volumes/${PACKAGE}"
